name: branch

on:
  push:
    branches-ignore: [main, gh-pages]
  workflow_dispatch:

permissions:
  packages: write
  id-token: write

jobs:
  build:
    env:
      VOLEXP_VG: vg0
      VOLEXP_NICS: '["eth0"]'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/cache@v4
      with:
        path: _cache
        key: ${{ runner.os }}-pip-${{ github.sha }}
        restore-keys: ${{ runner.os }}-pip-
    - uses: wtnb75/actions/python@main
      with:
        pipinstall: ".[dev]"
    - uses: wtnb75/actions/ruff@main
    - uses: wtnb75/actions/pytest@main
    - uses: wtnb75/actions/wheel@main
    - id: pdoc
      uses: wtnb75/actions/pdoc@main
      with:
        output-dir: docs
        module: volexport
    - uses: wtnb75/actions/merge-pages@main
      with:
        dirs: "cover docs"
        #pydist: dist
    - uses: wtnb75/actions/docker@main
      with:
        push: 'true'
        context: .
        username: ${{ github.actor }}
        password: ${{ github.token }}
        image-version: ${{ github.ref_name }}
