name: branch

on:
  push:
    branches-ignore: [main, gh-pages]
  workflow_dispatch:

permissions:
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VOLEXP_VG: vg0
      VOLEXP_NICS: '["eth0"]'
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: _cache
        key: ${{ runner.os }}-pip-${{ github.sha }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Install Task
      uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
    - uses: wtnb75/actions/python@c1711251ea69e3e6d68db7a9fa019d79b497f70c # v1.0.3
      with:
        pipinstall: ".[dev,csi]"
    - run: task -d volexpcsi build
    - uses: wtnb75/actions/ruff@c1711251ea69e3e6d68db7a9fa019d79b497f70c # v1.0.3
    - uses: wtnb75/actions/pytest@c1711251ea69e3e6d68db7a9fa019d79b497f70c # v1.0.3
    - uses: wtnb75/actions/wheel@c1711251ea69e3e6d68db7a9fa019d79b497f70c # v1.0.3
    - id: pdoc
      uses: wtnb75/actions/pdoc@c1711251ea69e3e6d68db7a9fa019d79b497f70c # v1.0.3
      with:
        output-dir: docs
        module: volexport
    - name: install node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
    - name: api spec
      shell: bash
      run: |
        mkdir -p api
        PYTHONPATH=. python -m volexport.main apispec --format yaml > api/api-spec.yaml
        npx @redocly/cli@latest build-docs api/api-spec.yaml -o api/index.html
    - uses: wtnb75/actions/merge-pages@c1711251ea69e3e6d68db7a9fa019d79b497f70c # v1.0.3
      with:
        dirs: "cover docs api"
        #pydist: dist
    - uses: wtnb75/actions/docker@c1711251ea69e3e6d68db7a9fa019d79b497f70c # v1.0.3
      with:
        push: 'true'
        context: .
        username: ${{ github.actor }}
        password: ${{ github.token }}
        image-version: ${{ github.ref_name }}
