name: branch

on:
  push:
    branches-ignore: [main, gh-pages]
  workflow_dispatch:

permissions:
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VOLEXP_VG: vg0
      VOLEXP_NICS: '["eth0"]'
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Install Task
      uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
    - uses: wtnb75/actions/python@9789197715f5a6b54a25832ce27193be50662266 # v1.0.4
      with:
        extra-args: "--extra csi"
    - run: uv run task -d volexpcsi build
    - uses: wtnb75/actions/ruff@9789197715f5a6b54a25832ce27193be50662266 # v1.0.4
    - uses: wtnb75/actions/pytest@9789197715f5a6b54a25832ce27193be50662266 # v1.0.4
    - uses: wtnb75/actions/wheel@9789197715f5a6b54a25832ce27193be50662266 # v1.0.4
    - id: pdoc
      uses: wtnb75/actions/pdoc@9789197715f5a6b54a25832ce27193be50662266 # v1.0.4
      with:
        output-dir: docs
        module: volexport
    - name: install node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
    - name: api spec
      shell: bash
      run: |
        mkdir -p api
        PYTHONPATH=. uv run python -m volexport.main apispec --format yaml > api/api-spec.yaml
        npx @redocly/cli@latest build-docs api/api-spec.yaml -o api/index.html
    - uses: wtnb75/actions/merge-pages@9789197715f5a6b54a25832ce27193be50662266 # v1.0.4
      with:
        dirs: "cover docs api"
        #pydist: dist
    - uses: wtnb75/actions/docker@9789197715f5a6b54a25832ce27193be50662266 # v1.0.4
      with:
        push: 'true'
        context: .
        username: ${{ github.actor }}
        password: ${{ github.token }}
        image-version: ${{ github.ref_name }}
