name: main

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  packages: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VOLEXP_VG: vg0
      VOLEXP_NICS: '["eth0"]'
    steps:
    - uses: actions/checkout@master
    - uses: actions/cache@v4
      with:
        path: _cache
        key: ${{ runner.os }}-pip-${{ github.sha }}
        restore-keys: ${{ runner.os }}-pip-
    - uses: wtnb75/actions/python@main
      with:
        pipinstall: ".[dev, csi]"
    - uses: wtnb75/actions/ruff@main
    - uses: wtnb75/actions/pytest@main
    - uses: wtnb75/actions/wheel@main
    - id: pdoc
      uses: wtnb75/actions/pdoc@main
      with:
        output-dir: docs
        module: volexport
    - name: install node
      uses: actions/setup-node@v4
    - name: api spec
      shell: bash
      run: |
        mkdir -p api
        PYTHONPATH=. python -m volexport.main apispec --format yaml > api/api-spec.yaml
        npx @redocly/cli@latest build-docs api/api-spec.yaml -o api/index.html
    - uses: wtnb75/actions/merge-pages@main
      with:
        dirs: "cover docs api"
        #pydist: dist
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: deploy pages
      uses: actions/deploy-pages@v4
      id: deployment
    - uses: wtnb75/actions/docker@main
      with:
        push: 'true'
        context: .
        username: ${{ github.actor }}
        password: ${{ github.token }}
        image-version: ${{ github.ref_name }}
