name: tag

on:
  push:
    tags:
    - 'v*'

permissions:
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VOLEXP_VG: vg0
      VOLEXP_NICS: '["eth0"]'
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Install Task
      uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
    - name: versioning
      run: "echo \"VERSION = '${GITHUB_REF##*/v}'\" > volexport/version.py"
    - uses: wtnb75/actions/python@v1
      with:
        extra-args: "--extra csi"
    - run: uv run task -d volexpcsi build
    - uses: wtnb75/actions/ruff@v1
    - uses: wtnb75/actions/pytest@v1
    - id: wheel
      uses: wtnb75/actions/wheel@v1
    - id: pdoc
      uses: wtnb75/actions/pdoc@v1
      with:
        output-dir: docs
        module: volexport
    - name: install node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
    - name: api spec
      shell: bash
      run: |
        mkdir -p api
        PYTHONPATH=. uv run python -m volexport.main apispec --format yaml > api/api-spec.yaml
        npx @redocly/cli@latest build-docs api/api-spec.yaml -o api/index.html
    - uses: wtnb75/actions/pypi-upload@9789197715f5a6b54a25832ce27193be50662266 # v1.0.4
      with:
        username: ${{ secrets.TWINE_USERNAME }}
        password: ${{ secrets.TWINE_PASSWORD }}
        file: dist/${{ steps.wheel.outputs.filename }}
    - uses: wtnb75/actions/docker@v1
      with:
        push: 'true'
        context: .
        username: ${{ github.actor }}
        password: ${{ github.token }}
        image-version: ${{ github.ref_name }}
